#! /usr/bin/zsh

install=$HOME/.note
paths=$install/data/path

if [[ -d $install ]]; then
	input="a"
	while [[ $input != "y" && $input != "n" ]]
	do
		echo "An installation already exists. Are you sure you want a fresh installation? (y/n)"
		read input
		if [[ $input == "y" ]]; then
			for file in $install/*
			do
				if [[ -d $file ]]; then
					rm -r $file
				else
					rm $file
				fi
			done

			rmdir $install
		fi
	done
else
    mkdir $install
    mkdir $install/{data,class}
    touch $install/data/{path,time}
fi

if (( $# == 1 )); then
	EDITOR=$1
fi
if [[ -z $EDITOR ]]; then
	which $EDITOR > /dev/null

	if (( $? != 0 )); then
		editors=(emacs vim vi nano pico)
		for editor in ${editors[*]}
		do
			which $editor > /dev/null
			if (( $? == 0 )); then
				EDITOR=$editor
				break
			fi
		done

		if (( $? != 0 )); then
			echo "No available editors"
			exit 1
		fi
	fi
fi

echo "touch:$(which touch)" >> $paths
echo "editor:$(which $EDITOR)" >> $paths
make note
sudo ln -s "$(pwd)/bin/note" /usr/local/bin/note
